language: csharp
solution: informant-core.sln
install:
  - nuget restore informant-core.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug informant-core.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./NUnitTests/bin/Debug/NUnitTests.dll